
;; kbd stuff

(defvar river-dvp-numbers-row
  '((nil "$" "dollar")
    ("1" "&" "ampersand")
    ("2" "[" "bracketleft")
    ("3" "{" "braceleft")
    ("4" "}" "braceright")
    ("5" "(" "parenleft")
    ("6" "=" "equal")
    ("7" "*" "asterisk")
    ("8" ")" "parenright")
    ("9" "+" "plus")
    ("0" "]" "bracketright")))

(defvar river-kbd-symbols-alist
  '(("<return>" "Return")
    ("RET" "Return")
    ("SPC" "Space")
    ("<tab>" "Tab")
    ("<escape>" "Escape")
    ("<left>" "Left")
    ("<right>" "Right")
    ("<up>" "Up")
    ("<down>" "Down")
    ("/" "Slash")
    ("," "Comma")
    ("." "Period")
    ("<mouse-left>" "BTN_LEFT")
    ("<mouse-right>" "BTN_RIGHT")
    ("<mouse-up>" "BTN_UP")
    ("<mouse-down>" "BTN_DOWN")
    ("<XF86AudioRaiseVolume>" "XF86AudioRaiseVolume")
    ("<XF86AudioLowerVolume>" "XF86AudioLowerVolume")
    ("<XF86AudioMute>" "XF86AudioMute")
    ("<XF86MonBrightnessUp>" "XF86MonBrightnessUp")
    ("<XF86MonBrightnessDown>" "XF86MonBrightnessDown")
    ("<XF86AudioPlay>" "XF86AudioPlay")
    ("<print>" "Print")
    ("<f12>" "F12")
    ("<f11>" "F11")
    ("<f10>" "F10")
    ("<f9>" "F9")
    ("<f8>" "F8")
    ("<f7>" "F7")
    ("<f6>" "F6")
    ("<f5>" "F5")
    ("<f4>" "F4")
    ("<f3>" "F3")
    ("<f2>" "F2")
    ("<f1>" "F1")
    ("$" "dollar")
    ("&" "ampersand")
    ("[" "bracketleft")
    ("{" "braceleft")
    ("}" "braceright")
    ("(" "parenleft")
    ("=" "equal")
    ("*" "asterisk")
    (")" "parenright")
    ("+" "plus")
    ("]" "bracketright")))

